[openai]
api_key = ""  # Fill this in your local environment only, not in version control

[aws]
access_key = ""
secret_key = ""

[amazon]
client_id = ""
client_secret = ""
access_token = ""

[rainforest]
api_key = "" 